version: '3.8'

services:
  data-processor:
    build: .
    container_name: data-processor-app
    ports:
      - "5000:5000"
    volumes:
      - ./test/data:/app/test/data
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: unless-stopped
    networks:
      - data-processor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:

networks:
  data-processor-network:
    driver: bridge